/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppAccount: typeof import('./components/pages/AppAccount.vue')['default']
    AppInfo: typeof import('./components/pages/AppInfo.vue')['default']
    AppLogin: typeof import('./components/pages/AppLogin.vue')['default']
    AppMailing: typeof import('./components/pages/AppMailing.vue')['default']
    AppNavigationDrawers: typeof import('./components/navigation/AppNavigationDrawers.vue')['default']
    AppToolBar: typeof import('./components/navigation/AppToolBar.vue')['default']
    AppUserForm: typeof import('./components/pages/AppUserForm.vue')['default']
    AppUsers: typeof import('./components/pages/AppUsers.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
